range = _{ ASCII_DIGIT* ~ ":" ~ ASCII_DIGIT+ }
dice = {  ^"d" ~ ( range | ASCII_DIGIT+ | "%" | ^"fate" | ^"f" ) }
die = { ASCII_DIGIT* ~ dice }

compare = _{ ( ">" | "<" )? ~ ASCII_DIGIT* }
reroll = { ^"r" ~ compare }
explode = { "!" ~ ( "!" | ^"p" )? ~ compare }
discard = { ( ^"d" | ^"k" ) ~ ( ^"h" | ^"l" )? ~ compare }
critical = { ^"c" ~ ( ^"s" | ^"f" )? ~ compare }
behaviours = _{ ( reroll | explode | discard | critical )* }

roll = { die ~ behaviours }